INSERT INTO productos (nombre, descripcion, categoria, precio) VALUES
('Sierra circular', 'Sierra potente para cortes precisos en madera', 'Herramientas Eléctricas', 550000),
('Escalera plegable', 'Escalera de aluminio con múltiples posiciones', 'Equipos de Construcción', 280000),
('Llave inglesa', 'Llave ajustable para diferentes tamaños de tuercas', 'Herramientas Manuales', 35000),
('Generador eléctrico portátil', 'Generador a gasolina de 3000W para obra', 'Maquinaria Pesada', 3200000),
('Rodillo para pintura', 'Rodillo de espuma para superficies lisas', 'Herramientas de Pintura', 12000),
('Atornillador eléctrico', 'Atornillador recargable con batería de litio', 'Herramientas Eléctricas', 430000),
('Carretilla metálica', 'Carretilla resistente para carga y traslado de materiales', 'Equipos de Construcción', 180000),
('Cinta métrica', 'Cinta métrica de 5 metros con carcasa de plástico', 'Herramientas Manuales', 9000),
('Compactadora vibratoria', 'Compactadora para suelos compactos y asfalto', 'Maquinaria Pesada', 2800000),
('Pistola de silicona', 'Pistola manual para aplicación de selladores', 'Herramientas de Pintura', 25000),
('Lijadora orbital', 'Lijadora para acabados finos en madera y metal', 'Herramientas Eléctricas', 260000),
('Andamio tubular', 'Andamio resistente para trabajos en altura', 'Equipos de Construcción', 750000),
('Destornillador de precisión', 'Set de destornilladores para trabajos delicados', 'Herramientas Manuales', 28000),
('Retroexcavadora', 'Máquina pesada para excavaciones y movimiento de tierra', 'Maquinaria Pesada', 5000000),
('Pistola pulverizadora HVLP', 'Pistola para pintura con alto control de flujo', 'Herramientas de Pintura', 240000),
('Sierra de calar', 'Sierra para cortes curvos en madera y plástico', 'Herramientas Eléctricas', 320000),
('Hormigonera', 'Mezcladora para concreto con capacidad de 140 litros', 'Equipos de Construcción', 1500000),
('Martillo perforador', 'Martillo para perforar concreto y mampostería', 'Herramientas Manuales', 90000),
('Excavadora hidráulica', 'Máquina para excavación pesada y movimiento de tierra', 'Maquinaria Pesada', 7000000),
('Pistola de aire comprimido', 'Herramienta para limpieza con aire a presión', 'Herramientas de Pintura', 80000);
