INSERT INTO productos (nombre, descripcion, categoria, precio) VALUES
('Taladro inalambrico', 'Taladro potente con bateria de litio', 'Herramientas Electricas', 350000),
('Andamio metalico', 'Andamio de aluminio ajustable de 2 niveles', 'Equipos de Construccion', 950000),
('Martillo de carpintero', 'Martillo de acero con mango antideslizante', 'Herramientas Manuales', 45000),
('Compactadora de suelo', 'Maquina para compactar tierra o grava', 'Maquinaria Pesada', 4200000),
('Pistola de pintura', 'Pistola pulverizadora para pintura automotriz', 'Herramientas de Pintura', 170000),
('Sierra circular', 'Sierra potente para cortes precisos en madera', 'Herramientas Electricas', 550000),
('Escalera plegable', 'Escalera de aluminio con multiples posiciones', 'Equipos de Construccion', 280000),
('Llave inglesa', 'Llave ajustable para diferentes tamaños de tuercas', 'Herramientas Manuales', 35000),
('Generador electrico portatil', 'Generador a gasolina de 3000W para obra', 'Maquinaria Pesada', 3200000),
('Rodillo para pintura', 'Rodillo de espuma para superficies lisas', 'Herramientas de Pintura', 12000),
('Atornillador electrico', 'Atornillador recargable con bateria de litio', 'Herramientas Electricas', 430000),
('Carretilla metalica', 'Carretilla resistente para carga y traslado de materiales', 'Equipos de Construccion', 180000),
('Cinta metrica', 'Cinta metrica de 5 metros con carcasa de plastico', 'Herramientas Manuales', 9000),
('Compactadora vibratoria', 'Compactadora para suelos compactos y asfalto', 'Maquinaria Pesada', 2800000),
('Pistola de silicona', 'Pistola manual para aplicacion de selladores', 'Herramientas de Pintura', 25000),
('Lijadora orbital', 'Lijadora para acabados finos en madera y metal', 'Herramientas Electricas', 260000),
('Andamio tubular', 'Andamio resistente para trabajos en altura', 'Equipos de Construccion', 750000),
('Destornillador de precision', 'Set de destornilladores para trabajos delicados', 'Herramientas Manuales', 28000),
('Retroexcavadora', 'Maquina pesada para excavaciones y movimiento de tierra', 'Maquinaria Pesada', 5000000),
('Pistola pulverizadora HVLP', 'Pistola para pintura con alto control de flujo', 'Herramientas de Pintura', 240000),
('Sierra de calar', 'Sierra para cortes curvos en madera y plastico', 'Herramientas Electricas', 320000),
('Hormigonera', 'Mezcladora para concreto con capacidad de 140 litros', 'Equipos de Construccion', 1500000),
('Martillo perforador', 'Martillo para perforar concreto y mamposteria', 'Herramientas Manuales', 90000),
('Excavadora hidraulica', 'Maquina para excavacion pesada y movimiento de tierra', 'Maquinaria Pesada', 7000000),
('Pistola de aire comprimido', 'Herramienta para limpieza con aire a presion', 'Herramientas de Pintura', 80000),
('Nivel laser', 'Nivel para mediciones precisas con laser rojo', 'Herramientas Electricas', 120000),
('Sierra de banco', 'Sierra para cortes rectos en madera y metal', 'Herramientas Electricas', 800000),
('Carro de herramientas', 'Carro movil para guardar herramientas', 'Equipos de Construccion', 260000),
('Cuchillo para yeso', 'Cuchillo para cortar y moldear yeso', 'Herramientas Manuales', 15000),
('Mini excavadora', 'Maquina compacta para excavaciones en espacios reducidos', 'Maquinaria Pesada', 6000000),
('Pistola de calor', 'Herramienta para aplicar calor y secar pinturas', 'Herramientas de Pintura', 90000),
('Taladro percutor', 'Taladro con funcion de percusion para concreto', 'Herramientas Electricas', 400000),
('Escuadra metalica', 'Herramienta para medir y marcar angulos rectos', 'Herramientas Manuales', 20000),
('Andamio movil', 'Andamio con ruedas para facil desplazamiento', 'Equipos de Construccion', 850000),
('Compactadora de asfalto', 'Maquina para compactar superficies asfalticas', 'Maquinaria Pesada', 3900000),
('Brocha para pintura', 'Brocha para aplicar pintura en paredes', 'Herramientas de Pintura', 8000),
('Pulidora electrica', 'Pulidora para acabados brillantes en superficies', 'Herramientas Electricas', 350000),
('Carretilla plastica', 'Carretilla ligera para transporte de materiales', 'Equipos de Construccion', 130000),
('Cortafríos', 'Herramienta para romper superficies duras', 'Herramientas Manuales', 28000),
('Cargador de bateria', 'Cargador para baterias de herramientas electricas', 'Herramientas Electricas', 70000),
('Pluma para pintura', 'Pluma fina para detalles en pintura', 'Herramientas de Pintura', 15000),
('Escuadra de madera', 'Escuadra para carpinteria y medicion', 'Herramientas Manuales', 12000),
('Mini cargadora', 'Maquina para carga y traslado de materiales', 'Maquinaria Pesada', 5500000),
('Andamio plegable', 'Andamio facil de armar y guardar', 'Equipos de Construccion', 630000),
('Raspador de pintura', 'Herramienta para remover pintura vieja', 'Herramientas de Pintura', 22000),
('Sierra sable', 'Sierra electrica para cortes en metal y madera', 'Herramientas Electricas', 420000),
('Llave de impacto', 'Herramienta para apretar y aflojar tuercas', 'Herramientas Electricas', 480000),
('Cuchillo de electricista', 'Cuchillo para cortar cables y aislar', 'Herramientas Manuales', 25000),
('Bomba de agua', 'Bomba para traslado de agua en obras', 'Maquinaria Pesada', 2000000),
('Rodillo para texturas', 'Rodillo para aplicar texturas en paredes', 'Herramientas de Pintura', 17000),
('Andamio de madera', 'Andamio resistente fabricado en madera', 'Equipos de Construccion', 580000),
('Taladro de banco', 'Taladro fijo para taller y carpinteria', 'Herramientas Electricas', 610000),
('Escalera telescopica', 'Escalera ajustable con varios niveles', 'Equipos de Construccion', 340000),
('Martillo demoledor', 'Herramienta electrica para demolición', 'Herramientas Electricas', 720000),
('Cincel para piedra', 'Herramienta para tallar piedra y concreto', 'Herramientas Manuales', 32000),
('Pistola pulverizadora electrica', 'Pistola para pintura con flujo electrico', 'Herramientas de Pintura', 210000),
('Raspador metalico', 'Herramienta para limpiar superficies metalicas', 'Herramientas Manuales', 18000),
('Carro mezclador', 'Carro para mezclar materiales de construccion', 'Equipos de Construccion', 1200000),
('Sierra de cinta', 'Sierra para cortes precisos en metal y madera', 'Herramientas Electricas', 870000),
('Cinta aislante', 'Cinta para aislar conexiones electricas', 'Herramientas Manuales', 5000),
('Mini cargadora frontal', 'Maquina para cargas pesadas en espacios reducidos', 'Maquinaria Pesada', 5300000),
('Taladro de impacto', 'Taladro potente con funcion de impacto', 'Herramientas Electricas', 460000),
('Brocha de cerdas', 'Brocha para pintura con cerdas naturales', 'Herramientas de Pintura', 13000),
('Nivel de burbuja', 'Nivel para medicion horizontal y vertical', 'Herramientas Manuales', 22000),
('Andamio de aluminio', 'Andamio ligero y resistente de aluminio', 'Equipos de Construccion', 920000),
('Cortadora de azulejos', 'Herramienta para cortes precisos en azulejos', 'Herramientas Manuales', 85000),
('Sierra circular de mano', 'Sierra portatil para trabajos rapidos', 'Herramientas Electricas', 510000),
('Martillo de goma', 'Martillo para golpes suaves sin dañar superficies', 'Herramientas Manuales', 27000),
('Compresor de aire', 'Compresor para herramientas neumáticas', 'Maquinaria Pesada', 2100000),
('Pistola para pintar automotriz', 'Pistola para pintura de autos con alta precision', 'Herramientas de Pintura', 190000),
('Carretilla de mano', 'Carretilla para transporte manual de materiales', 'Equipos de Construccion', 150000),
('Destornillador electrico', 'Destornillador recargable para uso general', 'Herramientas Electricas', 390000),
('Raspador para yeso', 'Herramienta para remover yeso de paredes', 'Herramientas Manuales', 17000),
('Sierra de inglete', 'Sierra para cortes angulados precisos', 'Herramientas Electricas', 670000),
('Cinta de medir', 'Cinta para mediciones largas y precisas', 'Herramientas Manuales', 11000),
('Mini excavadora compacta', 'Maquina para trabajos en espacios reducidos', 'Maquinaria Pesada', 5800000),
('Pistola de aire caliente', 'Herramienta para secado y moldeado', 'Herramientas de Pintura', 95000),
('Andamio para pintura', 'Andamio facil de mover para trabajos de pintura', 'Equipos de Construccion', 700000),
('Taladro percutor electrico', 'Taladro con modo percusion para materiales duros', 'Herramientas Electricas', 420000),
('Escalera de fibra', 'Escalera resistente a la electricidad', 'Equipos de Construccion', 310000),
('Martillo de bola', 'Martillo para trabajos metalurgicos y carpinteria', 'Herramientas Manuales', 29000),
('Cincel electrico', 'Herramienta electrica para tallado y demolición', 'Herramientas Electricas', 520000),
('Carro de carga', 'Carro para transportar materiales pesados', 'Equipos de Construccion', 160000),
('Sierra de sable electrica', 'Sierra para cortes rapidos y precisos', 'Herramientas Electricas', 450000),
('Llave de tubo', 'Llave para ajuste de tubos y conexiones', 'Herramientas Manuales', 23000),
('Bomba sumergible', 'Bomba para extraccion de agua en obras', 'Maquinaria Pesada', 1800000),
('Rodillo para esmalte', 'Rodillo para aplicar esmalte en superficies', 'Herramientas de Pintura', 14000),
('Escuadra ajustable', 'Herramienta para medir angulos variados', 'Herramientas Manuales', 25000),
('Compactadora manual', 'Herramienta para compactacion manual de suelos', 'Maquinaria Pesada', 3100000),
('Pistola para imprimacion', 'Pistola para aplicar imprimacion en superficies', 'Herramientas de Pintura', 230000);

